train_config:
  learn_rate: !!float 1e-4
  epochs: 1000

  losses:
    - convergence
  
  lambdas: [1.0]

  losses_kwargs:
    conv_sigma: 0.01  # smallest
    div_sigma: 0.1  # largest
    eik_sigma: 0.05  # inbetween
    barrier: 1.0  # keep close to sink
    sink: -1.0  # keep close to barrier