model:
  # make time mlp, use output as reference for time dims
  time_mlp:
    base_channels: 64
    time_dims: &tdims 128

  conv_backbone:
    # conv 1
    - in_channels: 256
      out_channels: 512
      time_dims: *tdims
      attn_heads: 8  # 256 / 32
      use_pooling: true

    # conv 2
    - in_channels: 512
      out_channels: 1024
      time_dims: *tdims
      attn_heads: 16  # 512 / 32
      use_pooling: true

  linear_backbone:
    # linear 1
    - in_features: 1024
      out_features: 512
      time_dims: *tdims

    # linear 2
    - in_features: 512
      out_features: 256
      time_dims: *tdims

name: "ped_car"